<?php

/**
 * Implementation of hook_civicrm_tabs()
 */
function ybcivi_civicrm_tabs ( &$tabs, $contactID ) {

	//initialize civicrm api
	civicrm_initialize();
	$config =& CRM_Core_Config::singleton( );
	require_once "api/v2/Contact.php";

	//get the contact for this page
	$params = array(
		'contact_id'=>$contactID,
	);
	$contacts = &civicrm_contact_get($params);

	//if the contact is a Program add the site staff tab
	if($contacts[$contactID]['contact_sub_type'] == 'Program') {
		$url = CRM_Utils_System::url( 'civicrm/sitestaff/' . $contactID);
		$tabs[] = array('id' => 'siteStaff',
										'url' => $url,
										'title' => "Site Staff",
										'weight' => 2);
	}
}

/**
 * Implementation of hook_menu()
 */

function ybcivi_menu() {
	$items = array();

	//Add an entry for the site staff menu
	$items['civicrm/sitestaff/%'] = array(
		'title' => 'Site Staff',
		'description' => 'staff for each site',
		'page callback' => 'ybcivi_site_staff_page',
		'page arguments' => array(2),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);

	return $items;
}

function ybcivi_site_staff_page($contactId) {
	//initialize civicrm api
	civicrm_initialize();
	$config =& CRM_Core_Config::singleton( );
	require_once "api/v2/Relationship.php";

	$params = array(
		'contact_id'=>$contactId,
	);

	//get the 'Site Staff is' relationships to the given contact
	$relationships = &civicrm_contact_relationship_get(
		$params, 
		array(),
		array('Site Staff is')
	);

	//Find the custom field Id
	$result = db_query("SELECT id, option_group_id FROM {civicrm_custom_field} WHERE name = '%s'", 'Relationship_Roles');
	$row = db_fetch_object($result);
	$custom = $row->id;
	$option_group_id = $row->option_group_id;

	//Fetch the display labels for the site staff roles
	//this is option group 83 in local database
	$result = db_query('SELECT label, value FROM {civicrm_option_value} WHERE option_group_id = %d ORDER BY weight', $option_group_id);

	//Initialize the role arrays with the label names
	$roles = array();
	while ($opt = db_fetch_object($result)) {
		$roles[$opt->value] = array(
			'label' => $opt->label,
			'contacts' => array(),
		);
	}
	//Add a 'staff' role to the end of the array, for staff which do not
	//have a special role
	$roles['staff'] = array(
		'label' => "Staff",
		'contacts' => array(),
	);

	//Add site staff to roles array
	foreach($relationships['result'] as $contact) {
		//skip inactive or past date roles, these can still be seen on the
		//relationships tab
		if($contact['is_active'] == '1' && ($contact['end_date'] == NULL || $contact['end_date'] > date('Y-m-d')) ) {

			//find the custom data set key
			$k = preg_grep("/^custom_" . $custom . "_/", array_keys($contact), 0);
			//preg_grep returns matchIndex -> array value.  In this case I just
			//want the value, so i reset the array (which sets the array pointer
			//to the first element of the array)
			$k = reset($k);

			if(count($contact[$k]) > 0) {
				//If there are values for the custom data field, add the contact
				//to the appropriate roles in the roles array
				foreach($contact[$k] as $key => $value) {
					if($value == 1)
						$roles[$key]['contacts'][] = $contact;
				}
			} else {
				//if the user has no custom data fields, then add them to the
				//general 'staff' role.
				$roles['staff']['contacts'][] = $contact;
			}
		}
	}

	//Theme the roles array using page_site_staff_page
	return theme('page_site_staff_page', $roles);
}

/**
 * Implementation of hook_theme()
 */

function ybcivi_theme() {
	//register pag_site_Staff_page to the theme engine
	return array(
		'page_site_staff_page' => array(
			'arguments' => array('roles' => null),
			'template' => 'page-site-staff-page',
			'path' => drupal_get_path('module', 'ybcivi'),
		),
	);
}

/**
 * Implementation of hook_views_query_alter()
 */

function ybcivi_views_query_alter ( &$view, &$query) {
	if($view->name == 'site_staff') {
		$view->query->add_where('adv_filter',
			"(civicrm_relationship.end_date IS NULL OR civicrm_relationship.end_date >= NOW())");
		$view->query->set_group_operator("AND");
	}
}


